---
abstract: 'A Mouse role for processing command line options'
author:
  - 'NAKAGAWA Masaki <masaki@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Exception: 0.21
  Test::More: 0.62
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MouseX-Getopt
no_index:
  directory:
    - inc
    - t
requires:
  Getopt::Long: 2.37
  Getopt::Long::Descriptive: 0.077
  Mouse: 0.39
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/gfx/Perl-MouseX-Getopt.git
version: 0.2201
